### ISSUE TITLE
Can't add Autoload: res:// is an invalid path. File does not exist.

### ISSUE THREAD

**Issue by JoshuaDietz** [hmans/Godot-RigidBody-Auto-Scaler#2]
Hello,
I've tried to install the plugin by:
1. Downloading everything from github
2. unpacking the zip
3. copying the whole folder to the "addons" directory of my project
4. going to the plugins section in my project settings and activating the plugin

Then I get the message 
```
Can't add Autoload:
res:// is an invalid path. File does not exist.
```

Also, the plugin does not seem to work then.

How can I fix this?

Thank you!

**Comment by hmans** [comment]
Please install the plugin through the Asset Library built into the editor. Also please note that this plugin only supports Godot 4.x.
